apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  auth-mongo-uri: "mongodb://mongodb:27017/auth-db"
  order-mongo-uri: "mongodb://mongodb:27017/orders-db"
  product-mongo-uri: "mongodb://mongodb:27017/products-db"